In [1]:
from datar.datasets import mtcars, iris
from datar.all import *

%run nb_helpers.py
nb_header(arrange)

[2021-06-21 11:17:02][datar][WARNING] Builtin name "min" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "max" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "sum" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "abs" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "round" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "all" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "any" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "re" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "filter" has been overriden by datar.
[2021-06-21 11:17:02][datar][WARNING] Builtin name "slice" has been overriden by datar.

### # arrange

##### orders the rows of a data frame by the values of selected columns.

The original API:
https://dplyr.tidyverse.org/reference/arrange.html

##### Args:
&emsp;&emsp;`_data`: A data frame
&emsp;&emsp;`*series`: Variables, or functions of variables.
&emsp;&emsp;&emsp;&emsp;Use desc() to sort a variable in descending order.

&emsp;&emsp;`_by_group`: If TRUE, will sort first by grouping variable.
&emsp;&emsp;&emsp;&emsp;Applies to grouped data frames only.

&emsp;&emsp;`**kwargs`: Name-value pairs that apply with mutate

##### Returns:
&emsp;&emsp;An object of the same type as _data.
&emsp;&emsp;The output has the following properties:
&emsp;&emsp;&emsp;&emsp;All rows appear in the output, but (usually) in a different place.
&emsp;&emsp;&emsp;&emsp;Columns are not modified.
&emsp;&emsp;&emsp;&emsp;Groups are not modified.
&emsp;&emsp;&emsp;&emsp;Data frame attributes are preserved.

In [2]:
arrange(mtcars, f.cyl, f.disp)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,<float64>,<int64>,<float64>,<int64>,<float64>,<float64>,<float64>,<int64>,<int64>,<int64>,<int64>
0,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
1,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
2,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
3,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
4,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
5,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
6,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
7,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
8,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
9,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
10,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
11,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
12,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
13,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
14,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
15,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
16,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
17,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
18,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
19,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
20,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
21,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
22,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
24,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
25,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
26,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
27,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
28,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
29,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
30,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
31,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4

In [3]:
mtcars >> arrange(desc(f.disp))

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,<float64>,<int64>,<float64>,<int64>,<float64>,<float64>,<float64>,<int64>,<int64>,<int64>,<int64>
0,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
1,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
2,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
3,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
6,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
7,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
8,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
9,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
10,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
11,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
15,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
16,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
17,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
18,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
19,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
20,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
21,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
22,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
23,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
24,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
25,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
26,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
27,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
29,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
30,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
31,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1

In [9]:
by_cyl = mtcars >> group_by(f.cyl)
by_cyl >> arrange(desc(f.wt))

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,<float64>,<int64>,<float64>,<int64>,<float64>,<float64>,<float64>,<int64>,<int64>,<int64>,<int64>
0,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
1,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
2,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
3,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
4,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
5,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
6,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
7,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
8,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
9,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
10,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
11,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
12,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
13,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
14,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
15,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
16,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
17,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
18,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
19,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
20,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
21,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
22,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
23,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
24,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
25,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
26,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
27,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
28,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
29,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
30,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
31,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2

In [10]:
by_cyl >> arrange(desc(f.wt), _by_group=True)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,<float64>,<int64>,<float64>,<int64>,<float64>,<float64>,<float64>,<int64>,<int64>,<int64>,<int64>
0,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
1,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
2,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
3,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
4,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
5,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
6,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
7,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
8,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
9,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
10,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
11,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
12,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
13,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
14,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
15,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
16,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
17,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
18,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
19,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
20,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
21,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
22,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
23,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
25,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
26,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
27,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
28,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
29,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
30,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
31,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4

In [6]:
# use subscription for f-expression
def tidy_eval_arrange(_data, var):
  return _data >> arrange(f[var])
  
tidy_eval_arrange(mtcars, 'mpg')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,<float64>,<int64>,<float64>,<int64>,<float64>,<float64>,<float64>,<int64>,<int64>,<int64>,<int64>
0,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
1,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
2,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
3,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
4,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
5,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
6,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
7,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
8,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
9,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
10,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
11,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
12,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
13,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
14,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
15,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
16,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
17,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
18,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
19,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
20,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
21,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
22,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
23,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
24,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
25,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
26,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
28,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
29,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
30,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
31,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1

In [7]:
iris >> arrange(across(starts_with("Sepal")))

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
        <float64>    <float64>     <float64>    <float64>   <object>
0             4.3          3.0           1.1          0.1     setosa
1             4.4          2.9           1.4          0.2     setosa
2             4.4          3.0           1.3          0.2     setosa
3             4.4          3.2           1.3          0.2     setosa
..            ...          ...           ...          ...        ...
4             4.5          2.3           1.3          0.3     setosa
145           7.7          2.6           6.9          2.3  virginica
146           7.7          2.8           6.7          2.0  virginica
147           7.7          3.0           6.1          2.3  virginica
148           7.7          3.8           6.7          2.2  virginica
149           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [8]:
iris >> arrange(across(starts_with("Sepal"), desc))

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
        <float64>    <float64>     <float64>    <float64>   <object>
0             7.9          3.8           6.4          2.0  virginica
1             7.7          3.8           6.7          2.2  virginica
2             7.7          3.0           6.1          2.3  virginica
3             7.7          2.8           6.7          2.0  virginica
..            ...          ...           ...          ...        ...
4             7.7          2.6           6.9          2.3  virginica
145           4.5          2.3           1.3          0.3     setosa
146           4.4          3.2           1.3          0.2     setosa
147           4.4          3.0           1.3          0.2     setosa
148           4.4          2.9           1.4          0.2     setosa
149           4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]